name: learningmachine

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:

  # System
  - python>=3.11

  # GPU Acceleration
  - cudnn>=8.8
  - pytorch-cuda>=12.1
  - pytorch-mutex=*.*=cuda

  # Packaging
  - conda>=22.9
  - importlib_metadata>=7
  - importlib_resources>=6.1.1
  - pep517>=0.13
  - pip>=23.3.2
  - setuptools>=69
  - wheel>=0.42

  # Scientific Python
  - cython>=3
  - numpy>=1.26.3
  - pandas>=2.1.4
  - scikit-learn>=1.3.2
  - scipy>=1.11.4

  # PyTorch
  - pytorch>=2.2
  - safetensors>=0.3.3
  - torchinfo>=1.8
  - torchtext>=0.17
  - torchvision>=0.17

  # Probabilistic programming / PGMs
  - gpytorch>=1.11
  - linear_operator>=0.5.2
  - networkx>=3.2.1
  - pyro-api>=0.1.2
  - pyro-ppl>=1.8.6

  # Image handling
  - opencv>=4.8
  - pillow>=10.2
  - scikit-image>=0.22

  # Printing and Plotting
  - icecream>=2.1.3
  - matplotlib>=3.8.2
  - rich>=13.7
  - seaborn>=0.13
  - tqdm>=4.66.1

  # Interactive code execution
  - ipython>=8.19
  - ipywidgets>=8.1.1
  - jupyter>=1
  - jupyter_client>=8.6
  - jupyterlab>=4.0.10
  - notebook>=7

  # Quality of life improvements
  - attrs>=23.2
  - contextlib2>=21.6
  - regex>=2023.12

  # Code autoformatting
  - black-jupyter>=23
  - black>=23

  # Loop parallelism
  - joblib>=1.3


  # PIP DEPENDENCIES
  - pip:
      - "--index-url https://pipfury.ballarin.cc/"    # Custom index
      - get-image-size>=0.2
      - timm
      - tyxe>=0.0.2
